//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_PZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOO_CitadelEntities1 : DbContext
    {
        public OOO_CitadelEntities1()
            : base("name=OOO_CitadelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<maker> maker { get; set; }
        public virtual DbSet<pasport> pasport { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
