//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_PZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Emp_id { get; set; }
        public string adress { get; set; }
        public int stor_id { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
